require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - '**/features/*'

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Style/NumericLiterals:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Documentation:
  Enabled: false
